version: '3'
services:
  nodejs:
    build: .
    ports:
      - "8080:8000"   
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: student_plataform
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3307:3307"
